# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python27:
      python.version: '2.7'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip setuptools
    pip install -e .
  displayName: 'Install dependencies'

- script: |
    pip install pytest
    # pytest-azurepipelines 0.6.0 modifies the nodeid on tests.
    # See https://github.com/tonybaloney/pytest-azurepipelines/issues/20 for details
    # In the meantime, use a patched version.
    # pip install pytest-azurepipelines
    pip install git+https://github.com/freakboy3742/pytest-azurepipelines.git@default-nodeid
    python setup.py test
  displayName: 'pytest'
